#ifndef __APP_CONFIG_H
#define __APP_CONFIG_H

#include "main.h"

#include <stdint.h>

/* LED 是低电平点亮：写 RESET 亮，写 SET 灭。 */
#define APP_LED_RUN_PIN GPIO_PIN_8
#define APP_LED_ALARM_PIN GPIO_PIN_7
#define APP_LED_APP_PIN GPIO_PIN_6
#define APP_LED_GPIO_PORT GPIOA
#define APP_LED_ON GPIO_PIN_RESET
#define APP_LED_OFF GPIO_PIN_SET

/* 两个按键都接了上拉，按下时读到 RESET。 */
#define APP_KEY_RUN_PIN GPIO_PIN_12
#define APP_KEY_DIR_PIN GPIO_PIN_13
#define APP_KEY_GPIO_PORT GPIOB
#define APP_KEY_PRESSED GPIO_PIN_RESET

#define APP_ADC_MAX_VALUE 4095U
#define APP_VREF_MV 3300U
#define APP_ADC_FILTER_SHIFT 2U
#define APP_ADC_FAIL_LIMIT 5U

#define APP_PWM_MAX_DUTY 100U
#define APP_MOTOR_MIN_START_DUTY 40U
#define APP_MOTOR_REVERSE_DELAY_MS 50U
#define APP_MOTOR_RAMP_STEP_DUTY 3U

#define APP_REPORT_PERIOD_DEFAULT_MS 1000U
#define APP_REPORT_PERIOD_MIN_MS 300U
#define APP_REPORT_PERIOD_MAX_MS 2000U
#define APP_CONTROL_PERIOD_MS 20U
#define APP_ALARM_VOLTAGE_MV 3000U
#define APP_ALARM_BLINK_HALF_PERIOD_MS 50U
#define APP_KEY_DEBOUNCE_MS 30U

#define APP_OLED_STATUS_UPDATE_PERIOD_MS 500U
#define APP_OLED_FORCE_REFRESH_PERIOD_MS 1000U
#define APP_OLED_LEFT_STATUS_WIDTH 9U
#define APP_OLED_SEPARATOR_X 72U
#define APP_OLED_SEPARATOR_WIDTH 8U

typedef enum
{
  APP_CONTROL_KEYS = 0,
  APP_CONTROL_FORCE_FORWARD,
  APP_CONTROL_FORCE_REVERSE,
  APP_CONTROL_FORCE_STOP,
  APP_CONTROL_TEST_FORWARD_100,
  APP_CONTROL_TEST_REVERSE_100
} AppControlMode_t;

#endif
